"""Pydantic schemas used by the server API and OpenAPI docs."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class StrictSchema(BaseModel):
    """Base schema that rejects unknown fields in requests and responses."""

    model_config = ConfigDict(extra="forbid")


class ErrorResponse(StrictSchema):
    """Error payload returned by API endpoints."""

    status: str = Field(default="error")
    message: str


class StatusMessageResponse(StrictSchema):
    """Generic success payload with a message field."""

    status: str = Field(default="ok")
    message: str


class HealthResponse(StrictSchema):
    """Health endpoint payload."""

    status: str = Field(default="ok")


class RegisterRequest(StrictSchema):
    """Request body used by self-registration endpoint."""

    username: str = Field(min_length=3, max_length=128, pattern=r"^[A-Za-z0-9_.-]+$")
    password: str = Field(min_length=8, max_length=128)


class LoginRequest(StrictSchema):
    """Request body used by login endpoint."""

    username: str = Field(min_length=1, max_length=128)
    password: str = Field(min_length=1, max_length=128)


class AuthResponse(StrictSchema):
    """Authentication success payload."""

    status: str = Field(default="ok")
    message: str
    username: str
    user_id: int


class SessionResponse(StrictSchema):
    """Session details for the currently logged-in user."""

    username: str
    user_id: int


class ModelAvailability(StrictSchema):
    """Model file availability for one bearing type."""

    model: str
    filename: str
    family: str
    available: bool


class ModelListResponse(StrictSchema):
    """List of model availability records for a bearing type."""

    bearing_type: str
    models: list[ModelAvailability]


class SensorResponse(StrictSchema):
    """Sensor record returned in dashboard API calls."""

    sensor_uid: str
    bearing_type: str
    selected_model: str
    is_active: bool
    connected: bool
    last_seen_at: datetime | None
    updated_at: datetime
    active_accel: str | None = None


class SensorCreateRequest(StrictSchema):
    """Request body for creating a sensor."""

    sensor_uid: str = Field(min_length=1, max_length=128)
    bearing_type: str = Field(default="underhang")
    selected_model: str = Field(default="LightGBM")


class SensorUpdateRequest(StrictSchema):
    """Request body for updating sensor bearing type, selected model, or accel preferences."""

    bearing_type: str | None = None
    selected_model: str | None = None
    active_accel: str | None = None


class SensorMutationResponse(StrictSchema):
    """Response body for sensor create/update operations."""

    status: str = Field(default="ok")
    sensor_uid: str
    bearing_type: str
    selected_model: str
    active_accel: str | None = None


class InferenceLatestRow(StrictSchema):
    """Single recent inference row returned in dashboard tables."""

    record_id: int
    sensor_uid: str
    bearing_type: str
    file_id: str
    selected_model: str
    selected_inference: str
    created_at: datetime
    avg: float | None = Field(
        default=None,
        description="Mean value of the normalized frequency spectrum magnitudes.",
    )
    std_dev: float | None = Field(
        default=None,
        description="Standard deviation of the normalized frequency spectrum magnitudes.",
    )
    current_ma: float | None = Field(
        default=None,
        description="Current in milliamps measured by the INA219 sensor at transmission time.",
    )
    model_results: dict[str, dict[str, Any]]


class FrequencyAnalysisResponse(StrictSchema):
    """Frequency-domain payload for dashboard charts."""

    freq_hz: list[float]
    underhang_mag: list[float]
    overhang_mag: list[float]
    message: str


class InferenceRequestPayload(StrictSchema):
    """Inference payload received from the middleware pipeline."""

    file_id: str = Field(
        description="Unique file identifier generated by the sensor for this transmission."
    )
    csv_data: str = Field(
        description=(
            "Raw CSV payload containing three comma-separated accelerometer columns (x, y, z). "
            "Each row represents one sample."
        )
    )
    checksum: str = Field(
        description="SHA-256 hex digest of csv_data for transmission integrity verification."
    )
    capture_sequence: int | None = Field(
        default=None,
        description="Monotonic capture counter shared by both LIS3DH/ADXL345 files from the same cycle.",
    )
    sensor_id: str | None = Field(
        default=None,
        description="Sensor UID used to resolve the sensor record and select the correct model.",
    )
    current_ma: float | None = Field(
        default=None,
        description="Current in milliamps measured by the INA219 sensor on the ESP32.",
    )
    sample_rate_hz: int | None = Field(
        default=None,
        description=(
            "Actual sample rate of the incoming CSV data in Hz. "
            "The server resamples to its 5000 Hz working rate before feature extraction."
        ),
    )


class InferenceResponsePayload(StrictSchema):
    """Inference payload returned to middleware and dashboard API clients."""

    status: str
    file_id: str
    sensor_id: str
    bearing_type: str
    selected_model: str
    inference: str
    model: str
    checksum_valid: bool
    avg: float = Field(
        description="Mean value of the normalized frequency spectrum magnitudes."
    )
    std_dev: float = Field(
        description="Standard deviation of the normalized frequency spectrum magnitudes."
    )
    current_ma: float | None = Field(
        default=None,
        description="Current in milliamps echoed from the request payload.",
    )
    sample_rate_hz: int | None = Field(
        default=None,
        description="Actual input sample rate echoed from the request.",
    )
    all_model_results: dict[str, dict[str, Any]]
    analysis: FrequencyAnalysisResponse
