idf_component_register(
    SRCS
        "main.c"
        "src/app/app.c"
        "src/app/app_init.c"
        "src/app/app_acquire.c"
        "src/app/app_send.c"
        "src/freertos/freertos-tasks.c"
        "src/peripherals/setup.c"
        "src/peripherals/lis3dh.c"
        "src/peripherals/adxl345.c"
        "src/peripherals/i2c_bus.c"
        "src/peripherals/ina219.c"
        "src/peripherals/ssd1306.c"
        "src/peripherals/latin_font.c"
        "src/transport/mqtt_transport.c"
    INCLUDE_DIRS
        "."
        "include"
        "src/app"
        "src/freertos"
        "src/peripherals"
        "src/peripherals/headers"
        "src/transport"
    REQUIRES
        nvs_flash
        spiffs
        esp_wifi
        esp_netif
        esp_event
        esp_http_server
        esp_http_client
        esp_driver_spi
        esp_driver_gpio
        esp_driver_i2c
        esp_timer
        mbedtls
        freertos
        log
        heap
        vfs
)
